package com.controllerface.bvge.substances;

public enum Element
{
    __("?"),

    H("HYDROGEN"),
    He("HELIUM"),
    Li("LITHIUM"),
    Be("BERYLLIUM"),
    B("BORON"),
    C("CARBON"),
    N("NITROGEN"),
    O("OXYGEN"),
    F("FLUORINE"),
    Ne("NEON"),
    Na("SODIUM"),
    Mg("MAGNESIUM"),
    Al("ALUMINUM"),
    Si("SILICON"),
    P("PHOSPHORUS"),
    S("SULFUR"),
    Cl("CHLORINE"),
    Ar("ARGON"),
    K("POTASSIUM"),
    Ca("CALCIUM"),
    Sc("SCANDIUM"),
    Ti("TITANIUM"),
    V("VANADIUM"),
    Cr("CHROMIUM"),
    Mn("MANGANESE"),
    Fe("IRON"),
    Co("COBALT"),
    Ni("NICKEL"),
    Cu("COPPER"),
    Zn("ZINC"),
    Ga("GALLIUM"),
    Ge("GERMANIUM"),
    As("ARSENIC"),
    Se("SELENIUM"),
    Br("BROMINE"),
    Kr("KRYPTON"),
    Rb("RUBIDIUM"),
    Sr("STRONTIUM"),
    Y("YTTRIUM"),
    Zr("ZIRCONIUM"),
    Nb("NIOBIUM"),
    Mo("MOLYBDENUM"),
    Tc("TECHNETIUM"),
    Ru("RUTHENIUM"),
    Rh("RHODIUM"),
    Pd("PALLADIUM"),
    Ag("SILVER"),
    Cd("CADMIUM"),
    In("INDIUM"),
    Sn("TIN"),
    Sb("ANTIMONY"),
    Te("TELLURIUM"),
    I("IODINE"),
    Xe("XENON"),
    Cs("CESIUM"),
    Ba("BARIUM"),
    La("LANTHANUM"),
    Ce("CERIUM"),
    Pr("PRASEODYMIUM"),
    Nd("NEODYMIUM"),
    Pm("PROMETHIUM"),
    Sm("SAMARIUM"),
    Eu("EUROPIUM"),
    Gd("GADOLINIUM"),
    Tb("TERBIUM"),
    Dy("DYSPROSIUM"),
    Ho("HOLMIUM"),
    Er("ERBIUM"),
    Tm("THULIUM"),
    Yb("YTTERBIUM"),
    Lu("LUTETIUM"),
    Hf("HAFNIUM"),
    Ta("TANTALUM"),
    W("TUNGSTEN"),
    Re("RHENIUM"),
    Os("OSMIUM"),
    Ir("IRIDIUM"),
    Pt("PLATINUM"),
    Au("GOLD"),
    Hg("MERCURY"),
    Tl("THALLIUM"),
    Pb("LEAD"),
    Bi("BISMUTH"),
    Po("POLONIUM"),
    At("ASTATINE"),
    Rn("RADON"),
    Fr("FRANCIUM"),
    Ra("RADIUM"),
    Ac("ACTINIUM"),
    Th("THORIUM"),
    Pa("PROTACTINIUM"),
    U("URANIUM"),
    Np("NEPTUNIUM"),
    Pu("PLUTONIUM"),
    Am("AMERICIUM"),
    Cm("CURIUM"),
    Bk("BERKELIUM"),
    Cf("CALIFORNIUM"),
    Es("EINSTEINIUM"),
    Fm("FERMIUM"),
    Md("MENDELEVIUM"),
    No("NOBELIUM"),
    Lr("LAWRENCIUM"),
    Rf("RUTHERFORDIUM"),
    Db("DUBNIUM"),
    Sg("SEABORGIUM"),
    Bh("BOHRIUM"),
    Hs("HASSIUM"),
    Mt("MEITNERIUM"),
    Ds("DARMSTADTIUM"),
    Rg("ROENTGENIUM"),
    Cn("COPERNICIUM"),
    Nh("NIHONIUM"),
    Fl("FLEROVIUM"),
    Mc("MOSCOVIUM"),
    Lv("LIVERMORIUM"),
    Ts("TENNESSINE"),
    Og("OGANESSON"),

    ;

    public final byte atomic_number;
    public final String full_name;

    Element(String full_name)
    {
        this.full_name = full_name;
        this.atomic_number = (byte) this.ordinal();
    }

    Element()
    {
        this.full_name = this.name();
        this.atomic_number = (byte) this.ordinal();
    }
}
