package com.controllerface.bvge.cl.buffers;

public enum MirrorBufferType implements BufferType
{
    MIRROR_ENTITY,
    MIRROR_ENTITY_FLAG,
    MIRROR_ENTITY_MODEL_ID,
    MIRROR_ENTITY_ROOT_HULL,
    MIRROR_EDGE,
    MIRROR_EDGE_FLAG,
    MIRROR_HULL,
    MIRROR_HULL_AABB,
    MIRROR_HULL_ENTITY_ID,
    MIRROR_HULL_FLAG,
    MIRROR_HULL_MESH_ID,
    MIRROR_HULL_UV_OFFSET,
    MIRROR_HULL_INTEGRITY,
    MIRROR_HULL_POINT_TABLE,
    MIRROR_HULL_ROTATION,
    MIRROR_HULL_SCALE,
    MIRROR_POINT,
    MIRROR_POINT_ANTI_GRAV,
    MIRROR_POINT_HIT_COUNT,
    MIRROR_POINT_VERTEX_REFERENCE,
}
