package com.controllerface.bvge.cl;

public enum BufferType
{
    EDGE,
    EDGE_FLAG,
    EDGE_LENGTH,
    HULL,
    HULL_MESH_ID,
    HULL_ROTATION,
    HULL_ELEMENT_TABLE,
    HULL_FLAG,
    HULL_AABB,
    HULL_AABB_INDEX,
    HULL_AABB_KEY_TABLE,
    HULL_BONE,
    HULL_BONE_TABLE,
    POINT,
    POINT_ANTI_GRAV,
    POINT_VERTEX_TABLE,
    POINT_BONE_TABLE,
    VERTEX_REFERENCE,
    VERTEX_WEIGHT,
    VERTEX_TEXTURE_UV,
    VERTEX_UV_TABLE,
}
